#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 1
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  sym__word = 1,
  anon_sym_EXTERNPROTO = 2,
  anon_sym_PROTO = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_comment = 8,
  sym_null = 9,
  anon_sym_TRUE = 10,
  anon_sym_FALSE = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  anon_sym_COMMA = 15,
  anon_sym_field = 16,
  anon_sym_unconnectedField = 17,
  anon_sym_vrmlField = 18,
  anon_sym_hiddenField = 19,
  anon_sym_DEF = 20,
  anon_sym_IS = 21,
  anon_sym_USE = 22,
  anon_sym_hidden = 23,
  anon_sym_PERCENT_LT = 24,
  anon_sym_PERCENT_LT_EQ = 25,
  anon_sym_GT_PERCENT = 26,
  sym__text_fragment = 27,
  sym_error_sentinel = 28,
  sym_source_file = 29,
  sym_extern = 30,
  sym_proto = 31,
  sym_identifier = 32,
  sym_boolean = 33,
  sym_string = 34,
  sym__vectorWithBrackets = 35,
  sym__vectorWithoutBrackets = 36,
  sym_vector = 37,
  sym__fieldType = 38,
  sym__fieldValue = 39,
  sym_field = 40,
  sym__value = 41,
  sym_class = 42,
  sym_property = 43,
  sym_javascript = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_source_file_repeat2 = 46,
  aux_sym_proto_repeat1 = 47,
  aux_sym__vectorWithBrackets_repeat1 = 48,
  aux_sym__vectorWithoutBrackets_repeat1 = 49,
  aux_sym__fieldType_repeat1 = 50,
  aux_sym_class_repeat1 = 51,
  alias_sym_type = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [anon_sym_EXTERNPROTO] = "EXTERNPROTO",
  [anon_sym_PROTO] = "PROTO",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [sym_null] = "null",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_field] = "field",
  [anon_sym_unconnectedField] = "unconnectedField",
  [anon_sym_vrmlField] = "vrmlField",
  [anon_sym_hiddenField] = "hiddenField",
  [anon_sym_DEF] = "DEF",
  [anon_sym_IS] = "IS",
  [anon_sym_USE] = "USE",
  [anon_sym_hidden] = "hidden",
  [anon_sym_PERCENT_LT] = "%<",
  [anon_sym_PERCENT_LT_EQ] = "%<=",
  [anon_sym_GT_PERCENT] = ">%",
  [sym__text_fragment] = "code",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_extern] = "extern",
  [sym_proto] = "proto",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym__vectorWithBrackets] = "_vectorWithBrackets",
  [sym__vectorWithoutBrackets] = "_vectorWithoutBrackets",
  [sym_vector] = "vector",
  [sym__fieldType] = "_fieldType",
  [sym__fieldValue] = "_fieldValue",
  [sym_field] = "field",
  [sym__value] = "_value",
  [sym_class] = "class",
  [sym_property] = "property",
  [sym_javascript] = "javascript",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_proto_repeat1] = "proto_repeat1",
  [aux_sym__vectorWithBrackets_repeat1] = "_vectorWithBrackets_repeat1",
  [aux_sym__vectorWithoutBrackets_repeat1] = "_vectorWithoutBrackets_repeat1",
  [aux_sym__fieldType_repeat1] = "_fieldType_repeat1",
  [aux_sym_class_repeat1] = "class_repeat1",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [anon_sym_EXTERNPROTO] = anon_sym_EXTERNPROTO,
  [anon_sym_PROTO] = anon_sym_PROTO,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [sym_null] = sym_null,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_unconnectedField] = anon_sym_unconnectedField,
  [anon_sym_vrmlField] = anon_sym_vrmlField,
  [anon_sym_hiddenField] = anon_sym_hiddenField,
  [anon_sym_DEF] = anon_sym_DEF,
  [anon_sym_IS] = anon_sym_IS,
  [anon_sym_USE] = anon_sym_USE,
  [anon_sym_hidden] = anon_sym_hidden,
  [anon_sym_PERCENT_LT] = anon_sym_PERCENT_LT,
  [anon_sym_PERCENT_LT_EQ] = anon_sym_PERCENT_LT_EQ,
  [anon_sym_GT_PERCENT] = anon_sym_GT_PERCENT,
  [sym__text_fragment] = sym__text_fragment,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_extern] = sym_extern,
  [sym_proto] = sym_proto,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym__vectorWithBrackets] = sym__vectorWithBrackets,
  [sym__vectorWithoutBrackets] = sym__vectorWithoutBrackets,
  [sym_vector] = sym_vector,
  [sym__fieldType] = sym__fieldType,
  [sym__fieldValue] = sym__fieldValue,
  [sym_field] = sym_field,
  [sym__value] = sym__value,
  [sym_class] = sym_class,
  [sym_property] = sym_property,
  [sym_javascript] = sym_javascript,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_proto_repeat1] = aux_sym_proto_repeat1,
  [aux_sym__vectorWithBrackets_repeat1] = aux_sym__vectorWithBrackets_repeat1,
  [aux_sym__vectorWithoutBrackets_repeat1] = aux_sym__vectorWithoutBrackets_repeat1,
  [aux_sym__fieldType_repeat1] = aux_sym__fieldType_repeat1,
  [aux_sym_class_repeat1] = aux_sym_class_repeat1,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EXTERNPROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unconnectedField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vrmlField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hiddenField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_USE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hidden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym__text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_proto] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__vectorWithBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym__vectorWithoutBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym__fieldType] = {
    .visible = false,
    .named = true,
  },
  [sym__fieldValue] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_javascript] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proto_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithoutBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__fieldType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_proto = 2,
  field_string_content = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_proto] = "proto",
  [field_string_content] = "string_content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_string_content, 1},
  [1] =
    {field_proto, 1},
  [2] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [1] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__fieldType, 2,
    sym__fieldType,
    alias_sym_type,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 18,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 41,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 52,
  [61] = 28,
  [62] = 21,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 75,
  [83] = 83,
  [84] = 80,
  [85] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 20,
        '#', 1,
        '%', 4,
        ',', 24,
        '.', 6,
        '>', 2,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
        '+', 3,
        '-', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'D', 1,
        'E', 2,
        'F', 3,
        'I', 4,
        'N', 5,
        'P', 6,
        'T', 7,
        'U', 8,
        'f', 9,
        'h', 10,
        'u', 11,
        'v', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'X') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'S') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'S') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'F') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'L') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_IS);
      END_STATE();
    case 17:
      if (lookahead == 'L') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'O') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DEF);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'S') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_USE);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'R') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'E') ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 39:
      if (lookahead == 'O') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_TRUE);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'F') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_FALSE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PROTO);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == 'P') ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_hidden);
      if (lookahead == 'F') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 56:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 60:
      if (lookahead == 'O') ADVANCE(64);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 63:
      if (lookahead == 'd') ADVANCE(67);
      END_STATE();
    case 64:
      if (lookahead == 'T') ADVANCE(68);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_vrmlField);
      END_STATE();
    case 68:
      if (lookahead == 'O') ADVANCE(71);
      END_STATE();
    case 69:
      if (lookahead == 'd') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EXTERNPROTO);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_hiddenField);
      END_STATE();
    case 73:
      if (lookahead == 'F') ADVANCE(74);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 76:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 77:
      if (lookahead == 'd') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_unconnectedField);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 22},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0, .external_lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0, .external_lex_state = 2},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [anon_sym_EXTERNPROTO] = ACTIONS(1),
    [anon_sym_PROTO] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_unconnectedField] = ACTIONS(1),
    [anon_sym_vrmlField] = ACTIONS(1),
    [anon_sym_hiddenField] = ACTIONS(1),
    [anon_sym_DEF] = ACTIONS(1),
    [anon_sym_IS] = ACTIONS(1),
    [anon_sym_USE] = ACTIONS(1),
    [anon_sym_hidden] = ACTIONS(1),
    [anon_sym_PERCENT_LT] = ACTIONS(1),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_PERCENT] = ACTIONS(1),
    [sym__text_fragment] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym_extern] = STATE(31),
    [sym_proto] = STATE(73),
    [sym_identifier] = STATE(70),
    [sym_class] = STATE(42),
    [sym_javascript] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(31),
    [aux_sym_source_file_repeat2] = STATE(42),
    [sym__word] = ACTIONS(5),
    [anon_sym_EXTERNPROTO] = ACTIONS(7),
    [anon_sym_PROTO] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PERCENT_LT] = ACTIONS(11),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      sym_null,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(5), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [63] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(37), 1,
      anon_sym_RBRACK,
    ACTIONS(39), 1,
      sym_null,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(7), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [126] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(45), 1,
      sym_null,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(2), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [189] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      sym_null,
    ACTIONS(61), 1,
      sym_number,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    ACTIONS(70), 1,
      anon_sym_DEF,
    ACTIONS(76), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(79), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(58), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(73), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(5), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [252] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym__word,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      anon_sym_RBRACK,
    ACTIONS(90), 1,
      sym_null,
    ACTIONS(96), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    ACTIONS(105), 1,
      anon_sym_DEF,
    ACTIONS(111), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(114), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(93), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(108), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(6), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [315] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    ACTIONS(119), 1,
      sym_null,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(6), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [378] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(121), 1,
      sym_null,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [437] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(123), 1,
      sym_null,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(51), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [496] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(125), 1,
      sym_null,
    ACTIONS(127), 1,
      sym_number,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(17), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(30), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [555] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(129), 1,
      sym_null,
    STATE(13), 1,
      sym_javascript,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(85), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(25), 4,
      sym_boolean,
      sym_string,
      sym_vector,
      sym_class,
  [606] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(131), 11,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [632] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(135), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [659] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_number,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(143), 5,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(141), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [690] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(151), 1,
      sym_null,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(153), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(27), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(63), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__fieldValue,
      sym_javascript,
  [733] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      sym_number,
    STATE(14), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(157), 5,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(155), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [764] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(161), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(165), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(169), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [841] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(171), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(175), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(141), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(179), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [937] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(183), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(135), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [985] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(187), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1009] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(191), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(195), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1057] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(199), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [1079] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [1101] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(7), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(9), 1,
      anon_sym_PROTO,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(60), 1,
      sym_javascript,
    STATE(70), 1,
      sym_identifier,
    STATE(77), 1,
      sym_proto,
    STATE(46), 2,
      sym_class,
      aux_sym_source_file_repeat2,
    STATE(49), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
  [1137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 5,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_PERCENT_LT,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
  [1157] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(209), 1,
      anon_sym_hidden,
    STATE(8), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
    STATE(38), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1186] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(209), 1,
      anon_sym_hidden,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
    STATE(38), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1215] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_javascript,
    STATE(50), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(40), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1244] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(209), 1,
      anon_sym_hidden,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
    STATE(34), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1273] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(209), 1,
      anon_sym_hidden,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
    STATE(33), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1302] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      sym__word,
    ACTIONS(224), 1,
      anon_sym_RBRACE,
    ACTIONS(226), 1,
      anon_sym_hidden,
    ACTIONS(229), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(232), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(8), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
    STATE(38), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1331] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(235), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_javascript,
    STATE(50), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(35), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1360] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym__word,
    ACTIONS(240), 1,
      anon_sym_RBRACK,
    ACTIONS(242), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(245), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(19), 1,
      sym_javascript,
    STATE(50), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(40), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1389] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      sym__word,
    ACTIONS(253), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(256), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(60), 1,
      sym_javascript,
    STATE(70), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1415] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_javascript,
    STATE(70), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1441] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    STATE(45), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1467] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    STATE(48), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1493] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    STATE(48), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1519] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_javascript,
    STATE(70), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1545] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    STATE(44), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1571] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    ACTIONS(250), 1,
      sym__word,
    ACTIONS(269), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(272), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(52), 1,
      sym_javascript,
    STATE(85), 1,
      sym_identifier,
    STATE(48), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1597] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(280), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(49), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
    ACTIONS(275), 3,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1616] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(19), 1,
      sym_javascript,
    STATE(53), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
  [1638] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(282), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(288), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(286), 3,
      anon_sym_RBRACE,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1666] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(15), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
  [1685] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(9), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
  [1704] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(19), 1,
      sym_javascript,
    STATE(72), 1,
      sym_identifier,
  [1723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(290), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1736] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(294), 4,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1749] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(19), 1,
      sym_javascript,
    STATE(20), 1,
      sym_identifier,
  [1768] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(213), 1,
      sym__word,
    STATE(11), 1,
      sym_identifier,
    STATE(19), 1,
      sym_javascript,
  [1787] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(288), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(286), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(197), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(298), 3,
      anon_sym_RBRACK,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1838] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    ACTIONS(306), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(302), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1852] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(308), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(312), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      sym_string,
  [1884] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      ts_builtin_sym_end,
  [1891] = 2,
    ACTIONS(318), 1,
      sym_comment,
    ACTIONS(320), 1,
      aux_sym_string_token1,
  [1898] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
  [1905] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [1912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_LBRACK,
  [1919] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
  [1926] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_LBRACE,
  [1933] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_GT_PERCENT,
  [1940] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      ts_builtin_sym_end,
  [1947] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
  [1954] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_DQUOTE,
  [1961] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
  [1968] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym__text_fragment,
  [1975] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_LBRACE,
  [1982] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_GT_PERCENT,
  [1989] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_number,
  [1996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym__text_fragment,
  [2003] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 189,
  [SMALL_STATE(6)] = 252,
  [SMALL_STATE(7)] = 315,
  [SMALL_STATE(8)] = 378,
  [SMALL_STATE(9)] = 437,
  [SMALL_STATE(10)] = 496,
  [SMALL_STATE(11)] = 555,
  [SMALL_STATE(12)] = 606,
  [SMALL_STATE(13)] = 632,
  [SMALL_STATE(14)] = 659,
  [SMALL_STATE(15)] = 690,
  [SMALL_STATE(16)] = 733,
  [SMALL_STATE(17)] = 764,
  [SMALL_STATE(18)] = 791,
  [SMALL_STATE(19)] = 816,
  [SMALL_STATE(20)] = 841,
  [SMALL_STATE(21)] = 865,
  [SMALL_STATE(22)] = 889,
  [SMALL_STATE(23)] = 913,
  [SMALL_STATE(24)] = 937,
  [SMALL_STATE(25)] = 961,
  [SMALL_STATE(26)] = 985,
  [SMALL_STATE(27)] = 1009,
  [SMALL_STATE(28)] = 1033,
  [SMALL_STATE(29)] = 1057,
  [SMALL_STATE(30)] = 1079,
  [SMALL_STATE(31)] = 1101,
  [SMALL_STATE(32)] = 1137,
  [SMALL_STATE(33)] = 1157,
  [SMALL_STATE(34)] = 1186,
  [SMALL_STATE(35)] = 1215,
  [SMALL_STATE(36)] = 1244,
  [SMALL_STATE(37)] = 1273,
  [SMALL_STATE(38)] = 1302,
  [SMALL_STATE(39)] = 1331,
  [SMALL_STATE(40)] = 1360,
  [SMALL_STATE(41)] = 1389,
  [SMALL_STATE(42)] = 1415,
  [SMALL_STATE(43)] = 1441,
  [SMALL_STATE(44)] = 1467,
  [SMALL_STATE(45)] = 1493,
  [SMALL_STATE(46)] = 1519,
  [SMALL_STATE(47)] = 1545,
  [SMALL_STATE(48)] = 1571,
  [SMALL_STATE(49)] = 1597,
  [SMALL_STATE(50)] = 1616,
  [SMALL_STATE(51)] = 1638,
  [SMALL_STATE(52)] = 1651,
  [SMALL_STATE(53)] = 1666,
  [SMALL_STATE(54)] = 1685,
  [SMALL_STATE(55)] = 1704,
  [SMALL_STATE(56)] = 1723,
  [SMALL_STATE(57)] = 1736,
  [SMALL_STATE(58)] = 1749,
  [SMALL_STATE(59)] = 1768,
  [SMALL_STATE(60)] = 1787,
  [SMALL_STATE(61)] = 1802,
  [SMALL_STATE(62)] = 1814,
  [SMALL_STATE(63)] = 1826,
  [SMALL_STATE(64)] = 1838,
  [SMALL_STATE(65)] = 1852,
  [SMALL_STATE(66)] = 1863,
  [SMALL_STATE(67)] = 1874,
  [SMALL_STATE(68)] = 1884,
  [SMALL_STATE(69)] = 1891,
  [SMALL_STATE(70)] = 1898,
  [SMALL_STATE(71)] = 1905,
  [SMALL_STATE(72)] = 1912,
  [SMALL_STATE(73)] = 1919,
  [SMALL_STATE(74)] = 1926,
  [SMALL_STATE(75)] = 1933,
  [SMALL_STATE(76)] = 1940,
  [SMALL_STATE(77)] = 1947,
  [SMALL_STATE(78)] = 1954,
  [SMALL_STATE(79)] = 1961,
  [SMALL_STATE(80)] = 1968,
  [SMALL_STATE(81)] = 1975,
  [SMALL_STATE(82)] = 1982,
  [SMALL_STATE(83)] = 1989,
  [SMALL_STATE(84)] = 1996,
  [SMALL_STATE(85)] = 2003,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_javascript, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_javascript, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 4, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 4, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 3, 0, 0),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [229] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [253] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(80),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(80),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(84),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(84),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 3),
  [300] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 4, 0, 3),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 1, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 1, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 4, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 4, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 3, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 3, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 6, 0, 2),
  [318] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 7, 0, 2),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 8, 0, 2),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__text_fragment = 0,
  ts_external_token_error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__text_fragment] = sym__text_fragment,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__text_fragment] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__text_fragment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_wbproto_external_scanner_create(void);
void tree_sitter_wbproto_external_scanner_destroy(void *);
bool tree_sitter_wbproto_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_wbproto_external_scanner_serialize(void *, char *);
void tree_sitter_wbproto_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wbproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_wbproto_external_scanner_create,
      tree_sitter_wbproto_external_scanner_destroy,
      tree_sitter_wbproto_external_scanner_scan,
      tree_sitter_wbproto_external_scanner_serialize,
      tree_sitter_wbproto_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
