#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 1
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  sym__word = 1,
  anon_sym_EXTERNPROTO = 2,
  anon_sym_PROTO = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_comment = 8,
  sym_null = 9,
  anon_sym_TRUE = 10,
  anon_sym_FALSE = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  anon_sym_COMMA = 15,
  anon_sym_field = 16,
  anon_sym_unconnectedField = 17,
  anon_sym_vrmlField = 18,
  anon_sym_hiddenField = 19,
  anon_sym_DEF = 20,
  anon_sym_IS = 21,
  anon_sym_USE = 22,
  anon_sym_hidden = 23,
  anon_sym_PERCENT_LT = 24,
  anon_sym_PERCENT_LT_EQ = 25,
  anon_sym_GT_PERCENT = 26,
  sym__text_fragment = 27,
  sym_error_sentinel = 28,
  sym_source_file = 29,
  sym_extern = 30,
  sym_proto = 31,
  sym_identifier = 32,
  sym_boolean = 33,
  sym_string = 34,
  sym__vectorWithBrackets = 35,
  sym__vectorWithoutBrackets = 36,
  sym_vector = 37,
  sym__fieldType = 38,
  sym__fieldValue = 39,
  sym_field = 40,
  sym__value = 41,
  sym_class = 42,
  sym_property = 43,
  sym_javascript = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_source_file_repeat2 = 46,
  aux_sym_proto_repeat1 = 47,
  aux_sym__vectorWithBrackets_repeat1 = 48,
  aux_sym__vectorWithoutBrackets_repeat1 = 49,
  aux_sym__fieldType_repeat1 = 50,
  aux_sym_class_repeat1 = 51,
  alias_sym_type = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [anon_sym_EXTERNPROTO] = "EXTERNPROTO",
  [anon_sym_PROTO] = "PROTO",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [sym_null] = "null",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_field] = "field",
  [anon_sym_unconnectedField] = "unconnectedField",
  [anon_sym_vrmlField] = "vrmlField",
  [anon_sym_hiddenField] = "hiddenField",
  [anon_sym_DEF] = "DEF",
  [anon_sym_IS] = "IS",
  [anon_sym_USE] = "USE",
  [anon_sym_hidden] = "hidden",
  [anon_sym_PERCENT_LT] = "%<",
  [anon_sym_PERCENT_LT_EQ] = "%<=",
  [anon_sym_GT_PERCENT] = ">%",
  [sym__text_fragment] = "code",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_extern] = "extern",
  [sym_proto] = "proto",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym__vectorWithBrackets] = "_vectorWithBrackets",
  [sym__vectorWithoutBrackets] = "_vectorWithoutBrackets",
  [sym_vector] = "vector",
  [sym__fieldType] = "_fieldType",
  [sym__fieldValue] = "_fieldValue",
  [sym_field] = "field",
  [sym__value] = "_value",
  [sym_class] = "class",
  [sym_property] = "property",
  [sym_javascript] = "javascript",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_proto_repeat1] = "proto_repeat1",
  [aux_sym__vectorWithBrackets_repeat1] = "_vectorWithBrackets_repeat1",
  [aux_sym__vectorWithoutBrackets_repeat1] = "_vectorWithoutBrackets_repeat1",
  [aux_sym__fieldType_repeat1] = "_fieldType_repeat1",
  [aux_sym_class_repeat1] = "class_repeat1",
  [alias_sym_type] = "type",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [anon_sym_EXTERNPROTO] = anon_sym_EXTERNPROTO,
  [anon_sym_PROTO] = anon_sym_PROTO,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [sym_null] = sym_null,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_unconnectedField] = anon_sym_unconnectedField,
  [anon_sym_vrmlField] = anon_sym_vrmlField,
  [anon_sym_hiddenField] = anon_sym_hiddenField,
  [anon_sym_DEF] = anon_sym_DEF,
  [anon_sym_IS] = anon_sym_IS,
  [anon_sym_USE] = anon_sym_USE,
  [anon_sym_hidden] = anon_sym_hidden,
  [anon_sym_PERCENT_LT] = anon_sym_PERCENT_LT,
  [anon_sym_PERCENT_LT_EQ] = anon_sym_PERCENT_LT_EQ,
  [anon_sym_GT_PERCENT] = anon_sym_GT_PERCENT,
  [sym__text_fragment] = sym__text_fragment,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_extern] = sym_extern,
  [sym_proto] = sym_proto,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym__vectorWithBrackets] = sym__vectorWithBrackets,
  [sym__vectorWithoutBrackets] = sym__vectorWithoutBrackets,
  [sym_vector] = sym_vector,
  [sym__fieldType] = sym__fieldType,
  [sym__fieldValue] = sym__fieldValue,
  [sym_field] = sym_field,
  [sym__value] = sym__value,
  [sym_class] = sym_class,
  [sym_property] = sym_property,
  [sym_javascript] = sym_javascript,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_proto_repeat1] = aux_sym_proto_repeat1,
  [aux_sym__vectorWithBrackets_repeat1] = aux_sym__vectorWithBrackets_repeat1,
  [aux_sym__vectorWithoutBrackets_repeat1] = aux_sym__vectorWithoutBrackets_repeat1,
  [aux_sym__fieldType_repeat1] = aux_sym__fieldType_repeat1,
  [aux_sym_class_repeat1] = aux_sym_class_repeat1,
  [alias_sym_type] = alias_sym_type,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EXTERNPROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unconnectedField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_vrmlField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hiddenField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_USE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hidden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym__text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_proto] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__vectorWithBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym__vectorWithoutBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym__fieldType] = {
    .visible = false,
    .named = true,
  },
  [sym__fieldValue] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_javascript] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proto_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithoutBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__fieldType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_type] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_proto = 2,
  field_string_content = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_proto] = "proto",
  [field_string_content] = "string_content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_string_content, 1},
  [1] =
    {field_proto, 1},
  [2] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [1] = alias_sym_type,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__fieldType, 2,
    sym__fieldType,
    alias_sym_type,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 14,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 42,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 58,
  [63] = 23,
  [64] = 64,
  [65] = 65,
  [66] = 26,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 71,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 81,
  [87] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 20,
        '#', 1,
        '%', 4,
        ',', 24,
        '.', 6,
        '>', 2,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
        '+', 3,
        '-', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'D', 1,
        'E', 2,
        'F', 3,
        'I', 4,
        'N', 5,
        'P', 6,
        'T', 7,
        'U', 8,
        'f', 9,
        'h', 10,
        'u', 11,
        'v', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'X') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'S') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'S') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'F') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'T') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'L') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_IS);
      END_STATE();
    case 17:
      if (lookahead == 'L') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'O') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DEF);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'S') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_USE);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'R') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'E') ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 39:
      if (lookahead == 'O') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_TRUE);
      END_STATE();
    case 41:
      if (lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'F') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'N') ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_FALSE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PROTO);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 52:
      if (lookahead == 'P') ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_hidden);
      if (lookahead == 'F') ADVANCE(57);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 56:
      if (lookahead == 'R') ADVANCE(60);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 58:
      if (lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 60:
      if (lookahead == 'O') ADVANCE(64);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(66);
      END_STATE();
    case 63:
      if (lookahead == 'd') ADVANCE(67);
      END_STATE();
    case 64:
      if (lookahead == 'T') ADVANCE(68);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 66:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_vrmlField);
      END_STATE();
    case 68:
      if (lookahead == 'O') ADVANCE(71);
      END_STATE();
    case 69:
      if (lookahead == 'd') ADVANCE(72);
      END_STATE();
    case 70:
      if (lookahead == 'd') ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EXTERNPROTO);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_hiddenField);
      END_STATE();
    case 73:
      if (lookahead == 'F') ADVANCE(74);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(75);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 76:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 77:
      if (lookahead == 'd') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_unconnectedField);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 22},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 2},
  [87] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [anon_sym_EXTERNPROTO] = ACTIONS(1),
    [anon_sym_PROTO] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_unconnectedField] = ACTIONS(1),
    [anon_sym_vrmlField] = ACTIONS(1),
    [anon_sym_hiddenField] = ACTIONS(1),
    [anon_sym_DEF] = ACTIONS(1),
    [anon_sym_IS] = ACTIONS(1),
    [anon_sym_USE] = ACTIONS(1),
    [anon_sym_hidden] = ACTIONS(1),
    [anon_sym_PERCENT_LT] = ACTIONS(1),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_PERCENT] = ACTIONS(1),
    [sym__text_fragment] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(80),
    [sym_extern] = STATE(32),
    [sym_proto] = STATE(79),
    [sym_identifier] = STATE(73),
    [sym_class] = STATE(44),
    [sym_javascript] = STATE(62),
    [aux_sym_source_file_repeat1] = STATE(32),
    [aux_sym_source_file_repeat2] = STATE(44),
    [sym__word] = ACTIONS(5),
    [anon_sym_EXTERNPROTO] = ACTIONS(7),
    [anon_sym_PROTO] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PERCENT_LT] = ACTIONS(11),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__word,
    ACTIONS(18), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 1,
      sym_null,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(32), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(38), 1,
      anon_sym_DEF,
    ACTIONS(44), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(47), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(26), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(41), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(2), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [61] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      anon_sym_RBRACK,
    ACTIONS(54), 1,
      sym_null,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_DEF,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(5), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [122] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_DEF,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(74), 1,
      sym_null,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(6), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [183] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_DEF,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    ACTIONS(80), 1,
      sym_null,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(2), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__vectorWithBrackets_repeat1,
  [244] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_DEF,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(84), 1,
      sym_null,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(7), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [305] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__word,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      sym_null,
    ACTIONS(100), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_DEF,
    ACTIONS(115), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(118), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(97), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(112), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(7), 6,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
      aux_sym__fieldType_repeat1,
  [366] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(64), 1,
      anon_sym_DEF,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      sym_null,
    ACTIONS(123), 1,
      sym_number,
    STATE(19), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(30), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [423] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      sym_null,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(129), 1,
      anon_sym_DEF,
    STATE(19), 1,
      sym_javascript,
    STATE(34), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(61), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [482] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(129), 1,
      anon_sym_DEF,
    ACTIONS(131), 1,
      sym_null,
    STATE(19), 1,
      sym_javascript,
    STATE(34), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(66), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(28), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(52), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [541] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      sym_null,
    STATE(17), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(28), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(21), 4,
      sym_boolean,
      sym_string,
      sym_vector,
      sym_class,
  [590] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(133), 1,
      sym_null,
    STATE(17), 1,
      sym_javascript,
    STATE(34), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(87), 1,
      sym_identifier,
    ACTIONS(56), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(28), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(21), 4,
      sym_boolean,
      sym_string,
      sym_vector,
      sym_class,
  [641] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(135), 11,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [667] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(139), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [692] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(127), 1,
      sym_number,
    ACTIONS(143), 1,
      sym_null,
    STATE(34), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(145), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(28), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(65), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__fieldValue,
      sym_javascript,
  [735] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_number,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(149), 5,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(147), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [766] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(157), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(163), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [818] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(167), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(165), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(169), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [869] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(157), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(147), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [917] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(173), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [941] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(177), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [965] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(181), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [989] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(185), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1013] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(189), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1037] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(193), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1061] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(197), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [1083] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(203), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [1105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 5,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_PERCENT_LT,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
  [1125] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(7), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(9), 1,
      anon_sym_PROTO,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(62), 1,
      sym_javascript,
    STATE(73), 1,
      sym_identifier,
    STATE(77), 1,
      sym_proto,
    STATE(48), 2,
      sym_class,
      aux_sym_source_file_repeat2,
    STATE(50), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
  [1161] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(207), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_javascript,
    STATE(51), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(37), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1190] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      sym_number,
    STATE(16), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(209), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
    ACTIONS(211), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
  [1213] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    ACTIONS(217), 1,
      anon_sym_hidden,
    STATE(9), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
    STATE(38), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1242] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(217), 1,
      anon_sym_hidden,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
    STATE(40), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1271] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_javascript,
    STATE(51), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(39), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1300] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(217), 1,
      anon_sym_hidden,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
    STATE(41), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1329] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      sym__word,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    ACTIONS(230), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(233), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(18), 1,
      sym_javascript,
    STATE(51), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
    STATE(39), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1358] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(217), 1,
      anon_sym_hidden,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
    STATE(41), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1387] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym__word,
    ACTIONS(241), 1,
      anon_sym_RBRACE,
    ACTIONS(243), 1,
      anon_sym_hidden,
    ACTIONS(246), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(249), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(9), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
    STATE(41), 2,
      sym_property,
      aux_sym_class_repeat1,
  [1416] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym__word,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    ACTIONS(257), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(260), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(58), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    STATE(42), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1442] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    STATE(42), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1468] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      sym_javascript,
    STATE(73), 1,
      sym_identifier,
    STATE(49), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1494] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    STATE(43), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1520] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    STATE(47), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1546] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_javascript,
    STATE(87), 1,
      sym_identifier,
    STATE(42), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1572] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      sym_javascript,
    STATE(73), 1,
      sym_identifier,
    STATE(49), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1598] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym__word,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(273), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(276), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(62), 1,
      sym_javascript,
    STATE(73), 1,
      sym_identifier,
    STATE(49), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1624] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(284), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(50), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
    ACTIONS(279), 3,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1643] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(18), 1,
      sym_javascript,
    STATE(56), 1,
      sym__fieldType,
    STATE(64), 1,
      sym_identifier,
  [1665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(286), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1678] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(12), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
  [1697] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(10), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
  [1716] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(11), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
  [1735] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(15), 1,
      sym_identifier,
    STATE(18), 1,
      sym_javascript,
  [1754] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(18), 1,
      sym_javascript,
    STATE(70), 1,
      sym_identifier,
  [1773] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(292), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(290), 3,
      anon_sym_RBRACE,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1788] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(70), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(205), 1,
      sym__word,
    STATE(18), 1,
      sym_javascript,
    STATE(20), 1,
      sym_identifier,
  [1807] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(294), 4,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1820] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(298), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1833] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(292), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(290), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1860] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LBRACE,
    ACTIONS(306), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(302), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1874] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(308), 3,
      anon_sym_RBRACK,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1886] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(187), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(312), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1909] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(316), 2,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1920] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_string,
  [1930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_LBRACK,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_GT_PERCENT,
  [1944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
  [1958] = 2,
    ACTIONS(328), 1,
      sym_comment,
    ACTIONS(330), 1,
      aux_sym_string_token1,
  [1965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_number,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      ts_builtin_sym_end,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
  [1986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_LBRACE,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
  [2000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      ts_builtin_sym_end,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym__text_fragment,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_GT_PERCENT,
  [2021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      ts_builtin_sym_end,
  [2028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_DQUOTE,
  [2035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
  [2042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      sym__text_fragment,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 122,
  [SMALL_STATE(5)] = 183,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 305,
  [SMALL_STATE(8)] = 366,
  [SMALL_STATE(9)] = 423,
  [SMALL_STATE(10)] = 482,
  [SMALL_STATE(11)] = 541,
  [SMALL_STATE(12)] = 590,
  [SMALL_STATE(13)] = 641,
  [SMALL_STATE(14)] = 667,
  [SMALL_STATE(15)] = 692,
  [SMALL_STATE(16)] = 735,
  [SMALL_STATE(17)] = 766,
  [SMALL_STATE(18)] = 793,
  [SMALL_STATE(19)] = 818,
  [SMALL_STATE(20)] = 845,
  [SMALL_STATE(21)] = 869,
  [SMALL_STATE(22)] = 893,
  [SMALL_STATE(23)] = 917,
  [SMALL_STATE(24)] = 941,
  [SMALL_STATE(25)] = 965,
  [SMALL_STATE(26)] = 989,
  [SMALL_STATE(27)] = 1013,
  [SMALL_STATE(28)] = 1037,
  [SMALL_STATE(29)] = 1061,
  [SMALL_STATE(30)] = 1083,
  [SMALL_STATE(31)] = 1105,
  [SMALL_STATE(32)] = 1125,
  [SMALL_STATE(33)] = 1161,
  [SMALL_STATE(34)] = 1190,
  [SMALL_STATE(35)] = 1213,
  [SMALL_STATE(36)] = 1242,
  [SMALL_STATE(37)] = 1271,
  [SMALL_STATE(38)] = 1300,
  [SMALL_STATE(39)] = 1329,
  [SMALL_STATE(40)] = 1358,
  [SMALL_STATE(41)] = 1387,
  [SMALL_STATE(42)] = 1416,
  [SMALL_STATE(43)] = 1442,
  [SMALL_STATE(44)] = 1468,
  [SMALL_STATE(45)] = 1494,
  [SMALL_STATE(46)] = 1520,
  [SMALL_STATE(47)] = 1546,
  [SMALL_STATE(48)] = 1572,
  [SMALL_STATE(49)] = 1598,
  [SMALL_STATE(50)] = 1624,
  [SMALL_STATE(51)] = 1643,
  [SMALL_STATE(52)] = 1665,
  [SMALL_STATE(53)] = 1678,
  [SMALL_STATE(54)] = 1697,
  [SMALL_STATE(55)] = 1716,
  [SMALL_STATE(56)] = 1735,
  [SMALL_STATE(57)] = 1754,
  [SMALL_STATE(58)] = 1773,
  [SMALL_STATE(59)] = 1788,
  [SMALL_STATE(60)] = 1807,
  [SMALL_STATE(61)] = 1820,
  [SMALL_STATE(62)] = 1833,
  [SMALL_STATE(63)] = 1848,
  [SMALL_STATE(64)] = 1860,
  [SMALL_STATE(65)] = 1874,
  [SMALL_STATE(66)] = 1886,
  [SMALL_STATE(67)] = 1898,
  [SMALL_STATE(68)] = 1909,
  [SMALL_STATE(69)] = 1920,
  [SMALL_STATE(70)] = 1930,
  [SMALL_STATE(71)] = 1937,
  [SMALL_STATE(72)] = 1944,
  [SMALL_STATE(73)] = 1951,
  [SMALL_STATE(74)] = 1958,
  [SMALL_STATE(75)] = 1965,
  [SMALL_STATE(76)] = 1972,
  [SMALL_STATE(77)] = 1979,
  [SMALL_STATE(78)] = 1986,
  [SMALL_STATE(79)] = 1993,
  [SMALL_STATE(80)] = 2000,
  [SMALL_STATE(81)] = 2007,
  [SMALL_STATE(82)] = 2014,
  [SMALL_STATE(83)] = 2021,
  [SMALL_STATE(84)] = 2028,
  [SMALL_STATE(85)] = 2035,
  [SMALL_STATE(86)] = 2042,
  [SMALL_STATE(87)] = 2049,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__fieldType_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_javascript, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_javascript, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 4, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 4, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 1, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0),
  [243] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(18),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(86),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(86),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [273] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(81),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(81),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 1, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 1, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 3),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 4, 0, 3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 3, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 3, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__fieldType, 4, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__fieldType, 4, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 7, 0, 2),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [330] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 8, 0, 2),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [338] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 6, 0, 2),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__text_fragment = 0,
  ts_external_token_error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__text_fragment] = sym__text_fragment,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__text_fragment] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__text_fragment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_wbproto_external_scanner_create(void);
void tree_sitter_wbproto_external_scanner_destroy(void *);
bool tree_sitter_wbproto_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_wbproto_external_scanner_serialize(void *, char *);
void tree_sitter_wbproto_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wbproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_wbproto_external_scanner_create,
      tree_sitter_wbproto_external_scanner_destroy,
      tree_sitter_wbproto_external_scanner_scan,
      tree_sitter_wbproto_external_scanner_serialize,
      tree_sitter_wbproto_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
