#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  sym__word = 1,
  anon_sym_EXTERNPROTO = 2,
  anon_sym_PROTO = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_comment = 8,
  sym_null = 9,
  anon_sym_TRUE = 10,
  anon_sym_FALSE = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  anon_sym_COMMA = 15,
  anon_sym_field = 16,
  anon_sym_unconnectedField = 17,
  anon_sym_DEF = 18,
  anon_sym_IS = 19,
  anon_sym_USE = 20,
  anon_sym_hidden = 21,
  anon_sym_PERCENT_LT = 22,
  anon_sym_PERCENT_LT_EQ = 23,
  anon_sym_GT_PERCENT = 24,
  sym__text_fragment = 25,
  sym_error_sentinel = 26,
  sym_source_file = 27,
  sym_extern = 28,
  sym_proto = 29,
  sym_identifier = 30,
  sym_boolean = 31,
  sym_string = 32,
  sym__vectorWithBrackets = 33,
  sym__vectorWithoutBrackets = 34,
  sym_vector = 35,
  sym__fieldType = 36,
  sym__fieldValue = 37,
  sym_field = 38,
  sym__value = 39,
  sym_class = 40,
  sym_property = 41,
  sym_javascript = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_source_file_repeat2 = 44,
  aux_sym_proto_repeat1 = 45,
  aux_sym__vectorWithBrackets_repeat1 = 46,
  aux_sym__vectorWithoutBrackets_repeat1 = 47,
  aux_sym_class_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__word] = "_word",
  [anon_sym_EXTERNPROTO] = "EXTERNPROTO",
  [anon_sym_PROTO] = "PROTO",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_comment] = "comment",
  [sym_null] = "null",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_COMMA] = ",",
  [anon_sym_field] = "field",
  [anon_sym_unconnectedField] = "unconnectedField",
  [anon_sym_DEF] = "DEF",
  [anon_sym_IS] = "IS",
  [anon_sym_USE] = "USE",
  [anon_sym_hidden] = "hidden",
  [anon_sym_PERCENT_LT] = "%<",
  [anon_sym_PERCENT_LT_EQ] = "%<=",
  [anon_sym_GT_PERCENT] = ">%",
  [sym__text_fragment] = "code",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym_extern] = "extern",
  [sym_proto] = "proto",
  [sym_identifier] = "identifier",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym__vectorWithBrackets] = "_vectorWithBrackets",
  [sym__vectorWithoutBrackets] = "_vectorWithoutBrackets",
  [sym_vector] = "vector",
  [sym__fieldType] = "_fieldType",
  [sym__fieldValue] = "_fieldValue",
  [sym_field] = "field",
  [sym__value] = "_value",
  [sym_class] = "class",
  [sym_property] = "property",
  [sym_javascript] = "javascript",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_proto_repeat1] = "proto_repeat1",
  [aux_sym__vectorWithBrackets_repeat1] = "_vectorWithBrackets_repeat1",
  [aux_sym__vectorWithoutBrackets_repeat1] = "_vectorWithoutBrackets_repeat1",
  [aux_sym_class_repeat1] = "class_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__word] = sym__word,
  [anon_sym_EXTERNPROTO] = anon_sym_EXTERNPROTO,
  [anon_sym_PROTO] = anon_sym_PROTO,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_comment] = sym_comment,
  [sym_null] = sym_null,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_unconnectedField] = anon_sym_unconnectedField,
  [anon_sym_DEF] = anon_sym_DEF,
  [anon_sym_IS] = anon_sym_IS,
  [anon_sym_USE] = anon_sym_USE,
  [anon_sym_hidden] = anon_sym_hidden,
  [anon_sym_PERCENT_LT] = anon_sym_PERCENT_LT,
  [anon_sym_PERCENT_LT_EQ] = anon_sym_PERCENT_LT_EQ,
  [anon_sym_GT_PERCENT] = anon_sym_GT_PERCENT,
  [sym__text_fragment] = sym__text_fragment,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_extern] = sym_extern,
  [sym_proto] = sym_proto,
  [sym_identifier] = sym_identifier,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym__vectorWithBrackets] = sym__vectorWithBrackets,
  [sym__vectorWithoutBrackets] = sym__vectorWithoutBrackets,
  [sym_vector] = sym_vector,
  [sym__fieldType] = sym__fieldType,
  [sym__fieldValue] = sym__fieldValue,
  [sym_field] = sym_field,
  [sym__value] = sym__value,
  [sym_class] = sym_class,
  [sym_property] = sym_property,
  [sym_javascript] = sym_javascript,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_proto_repeat1] = aux_sym_proto_repeat1,
  [aux_sym__vectorWithBrackets_repeat1] = aux_sym__vectorWithBrackets_repeat1,
  [aux_sym__vectorWithoutBrackets_repeat1] = aux_sym__vectorWithoutBrackets_repeat1,
  [aux_sym_class_repeat1] = aux_sym_class_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EXTERNPROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PROTO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unconnectedField] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_USE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hidden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym__text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_proto] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__vectorWithBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym__vectorWithoutBrackets] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym__fieldType] = {
    .visible = false,
    .named = true,
  },
  [sym__fieldValue] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_javascript] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proto_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__vectorWithoutBrackets_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_proto = 2,
  field_string_content = 3,
  field_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_proto] = "proto",
  [field_string_content] = "string_content",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_string_content, 1},
  [1] =
    {field_proto, 1},
  [2] =
    {field_name, 2},
    {field_type, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 20,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 31,
  [34] = 34,
  [35] = 32,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 50,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 52,
  [60] = 23,
  [61] = 25,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 65,
  [77] = 77,
  [78] = 78,
  [79] = 75,
  [80] = 66,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 20,
        '#', 1,
        '%', 4,
        ',', 24,
        '.', 6,
        '>', 2,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
        '+', 3,
        '-', 3,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'i' ||
          lookahead == 'j') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '#') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_PERCENT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'D', 1,
        'E', 2,
        'F', 3,
        'I', 4,
        'N', 5,
        'P', 6,
        'T', 7,
        'U', 8,
        'f', 9,
        'h', 10,
        'u', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'X') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'S') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'S') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 'F') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'L') ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_IS);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'U') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DEF);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'S') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'T') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_USE);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(41);
      END_STATE();
    case 34:
      if (lookahead == 'E') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 36:
      if (lookahead == 'O') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_TRUE);
      END_STATE();
    case 38:
      if (lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 41:
      if (lookahead == 'N') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_FALSE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PROTO);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 47:
      if (lookahead == 'P') ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_hidden);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 50:
      if (lookahead == 'R') ADVANCE(52);
      END_STATE();
    case 51:
      if (lookahead == 'c') ADVANCE(53);
      END_STATE();
    case 52:
      if (lookahead == 'O') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 54:
      if (lookahead == 'T') ADVANCE(56);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 56:
      if (lookahead == 'O') ADVANCE(58);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_EXTERNPROTO);
      END_STATE();
    case 59:
      if (lookahead == 'F') ADVANCE(60);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 63:
      if (lookahead == 'd') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_unconnectedField);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 22},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0, .external_lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__word] = ACTIONS(1),
    [anon_sym_EXTERNPROTO] = ACTIONS(1),
    [anon_sym_PROTO] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_unconnectedField] = ACTIONS(1),
    [anon_sym_DEF] = ACTIONS(1),
    [anon_sym_IS] = ACTIONS(1),
    [anon_sym_USE] = ACTIONS(1),
    [anon_sym_hidden] = ACTIONS(1),
    [anon_sym_PERCENT_LT] = ACTIONS(1),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_PERCENT] = ACTIONS(1),
    [sym__text_fragment] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(74),
    [sym_extern] = STATE(29),
    [sym_proto] = STATE(73),
    [sym_identifier] = STATE(66),
    [sym_class] = STATE(36),
    [sym_javascript] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(29),
    [aux_sym_source_file_repeat2] = STATE(36),
    [sym__word] = ACTIONS(5),
    [anon_sym_EXTERNPROTO] = ACTIONS(7),
    [anon_sym_PROTO] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_PERCENT_LT] = ACTIONS(11),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(13),
  },
  [2] = {
    [sym_identifier] = STATE(80),
    [sym_boolean] = STATE(4),
    [sym_string] = STATE(4),
    [sym__vectorWithBrackets] = STATE(14),
    [sym__vectorWithoutBrackets] = STATE(14),
    [sym_vector] = STATE(4),
    [sym__value] = STATE(4),
    [sym_class] = STATE(4),
    [sym_javascript] = STATE(19),
    [aux_sym__vectorWithBrackets_repeat1] = STATE(4),
    [aux_sym__vectorWithoutBrackets_repeat1] = STATE(14),
    [sym__word] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(19),
    [anon_sym_TRUE] = ACTIONS(21),
    [anon_sym_FALSE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DEF] = ACTIONS(29),
    [anon_sym_IS] = ACTIONS(31),
    [anon_sym_USE] = ACTIONS(31),
    [anon_sym_PERCENT_LT] = ACTIONS(33),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(35),
  },
  [3] = {
    [sym_identifier] = STATE(80),
    [sym_boolean] = STATE(3),
    [sym_string] = STATE(3),
    [sym__vectorWithBrackets] = STATE(14),
    [sym__vectorWithoutBrackets] = STATE(14),
    [sym_vector] = STATE(3),
    [sym__value] = STATE(3),
    [sym_class] = STATE(3),
    [sym_javascript] = STATE(19),
    [aux_sym__vectorWithBrackets_repeat1] = STATE(3),
    [aux_sym__vectorWithoutBrackets_repeat1] = STATE(14),
    [sym__word] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(45),
    [anon_sym_TRUE] = ACTIONS(48),
    [anon_sym_FALSE] = ACTIONS(48),
    [sym_number] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(54),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_DEF] = ACTIONS(60),
    [anon_sym_IS] = ACTIONS(63),
    [anon_sym_USE] = ACTIONS(63),
    [anon_sym_PERCENT_LT] = ACTIONS(66),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(69),
  },
  [4] = {
    [sym_identifier] = STATE(80),
    [sym_boolean] = STATE(3),
    [sym_string] = STATE(3),
    [sym__vectorWithBrackets] = STATE(14),
    [sym__vectorWithoutBrackets] = STATE(14),
    [sym_vector] = STATE(3),
    [sym__value] = STATE(3),
    [sym_class] = STATE(3),
    [sym_javascript] = STATE(19),
    [aux_sym__vectorWithBrackets_repeat1] = STATE(3),
    [aux_sym__vectorWithoutBrackets_repeat1] = STATE(14),
    [sym__word] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
    [sym_null] = ACTIONS(74),
    [anon_sym_TRUE] = ACTIONS(21),
    [anon_sym_FALSE] = ACTIONS(21),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DEF] = ACTIONS(29),
    [anon_sym_IS] = ACTIONS(31),
    [anon_sym_USE] = ACTIONS(31),
    [anon_sym_PERCENT_LT] = ACTIONS(33),
    [anon_sym_PERCENT_LT_EQ] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(76), 1,
      sym_null,
    ACTIONS(78), 1,
      sym_number,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_DEF,
    STATE(19), 1,
      sym_javascript,
    STATE(30), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(14), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(49), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [59] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(78), 1,
      sym_number,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_DEF,
    ACTIONS(84), 1,
      sym_null,
    STATE(19), 1,
      sym_javascript,
    STATE(30), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(14), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(53), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [118] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DEF,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(86), 1,
      sym_null,
    ACTIONS(88), 1,
      sym_number,
    STATE(19), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    ACTIONS(31), 2,
      anon_sym_IS,
      anon_sym_USE,
    STATE(14), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(28), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__value,
      sym_class,
  [175] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(90), 13,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [203] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_number,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(94), 1,
      sym_null,
    STATE(17), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(14), 3,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(24), 4,
      sym_boolean,
      sym_string,
      sym_vector,
      sym_class,
  [252] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym_number,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(98), 5,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(96), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [285] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(78), 1,
      sym_number,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(94), 1,
      sym_null,
    STATE(17), 1,
      sym_javascript,
    STATE(30), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    STATE(80), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(14), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(24), 4,
      sym_boolean,
      sym_string,
      sym_vector,
      sym_class,
  [336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(96), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(106), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(110), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [414] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(114), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [440] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(118), 11,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [466] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(122), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [493] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      sym_number,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      sym_null,
    STATE(30), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(130), 2,
      anon_sym_TRUE,
      anon_sym_FALSE,
    STATE(14), 2,
      sym__vectorWithBrackets,
      sym__vectorWithoutBrackets,
    STATE(62), 5,
      sym_boolean,
      sym_string,
      sym_vector,
      sym__fieldValue,
      sym_javascript,
  [536] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(132), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(136), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 8,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(140), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [613] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(142), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [637] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(146), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [661] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(122), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 7,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(150), 9,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [709] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 7,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_PERCENT_LT,
    ACTIONS(138), 8,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(154), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_COMMA,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(160), 8,
      sym__word,
      sym_null,
      anon_sym_TRUE,
      anon_sym_FALSE,
      anon_sym_DEF,
      anon_sym_IS,
      anon_sym_USE,
      anon_sym_PERCENT_LT,
  [776] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(7), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(9), 1,
      anon_sym_PROTO,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(59), 1,
      sym_javascript,
    STATE(66), 1,
      sym_identifier,
    STATE(72), 1,
      sym_proto,
    STATE(40), 2,
      sym_class,
      aux_sym_source_file_repeat2,
    STATE(44), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
  [812] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      sym_number,
    STATE(10), 1,
      aux_sym__vectorWithoutBrackets_repeat1,
    ACTIONS(164), 3,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(162), 5,
      sym__word,
      anon_sym_field,
      anon_sym_unconnectedField,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [837] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    ACTIONS(170), 1,
      anon_sym_hidden,
    STATE(6), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
    STATE(34), 2,
      sym_property,
      aux_sym_class_repeat1,
  [866] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(170), 1,
      anon_sym_hidden,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
    STATE(31), 2,
      sym_property,
      aux_sym_class_repeat1,
  [895] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(170), 1,
      anon_sym_hidden,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
    STATE(34), 2,
      sym_property,
      aux_sym_class_repeat1,
  [924] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym__word,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      anon_sym_hidden,
    ACTIONS(184), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(187), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(6), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
    STATE(34), 2,
      sym_property,
      aux_sym_class_repeat1,
  [953] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__word,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(170), 1,
      anon_sym_hidden,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
    STATE(33), 2,
      sym_property,
      aux_sym_class_repeat1,
  [982] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 1,
      sym__word,
    STATE(59), 1,
      sym_javascript,
    STATE(66), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1008] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    STATE(39), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1034] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    STATE(43), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1060] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    STATE(43), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1086] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(59), 1,
      sym_javascript,
    STATE(66), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1112] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 1,
      sym__word,
    ACTIONS(207), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(210), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(59), 1,
      sym_javascript,
    STATE(66), 1,
      sym_identifier,
    STATE(41), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1138] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(52), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    STATE(38), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1164] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 1,
      sym__word,
    ACTIONS(215), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(218), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(52), 1,
      sym_javascript,
    STATE(80), 1,
      sym_identifier,
    STATE(43), 2,
      sym_class,
      aux_sym_source_file_repeat2,
  [1190] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_EXTERNPROTO,
    ACTIONS(226), 1,
      anon_sym_PERCENT_LT_EQ,
    STATE(44), 2,
      sym_extern,
      aux_sym_source_file_repeat1,
    ACTIONS(221), 3,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1209] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym__fieldType,
    ACTIONS(230), 2,
      anon_sym_field,
      anon_sym_unconnectedField,
    STATE(46), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1227] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym__fieldType,
    ACTIONS(230), 2,
      anon_sym_field,
      anon_sym_unconnectedField,
    STATE(47), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1245] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym__fieldType,
    ACTIONS(236), 2,
      anon_sym_field,
      anon_sym_unconnectedField,
    STATE(47), 2,
      sym_field,
      aux_sym_proto_repeat1,
  [1263] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(21), 1,
      sym_javascript,
    STATE(22), 1,
      sym_identifier,
  [1282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(239), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1295] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(9), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
  [1314] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(18), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
  [1333] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(243), 3,
      anon_sym_RBRACE,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 2,
      anon_sym_RBRACE,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(247), 3,
      sym__word,
      anon_sym_hidden,
      anon_sym_PERCENT_LT,
  [1361] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(5), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
  [1380] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(11), 1,
      sym_identifier,
    STATE(21), 1,
      sym_javascript,
  [1399] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(13), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(21), 1,
      sym_javascript,
    STATE(64), 1,
      sym_identifier,
  [1418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(251), 4,
      anon_sym_EXTERNPROTO,
      anon_sym_PROTO,
      sym__word,
      anon_sym_PERCENT_LT,
  [1431] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(35), 1,
      anon_sym_PERCENT_LT_EQ,
    ACTIONS(194), 1,
      sym__word,
    STATE(21), 1,
      sym_javascript,
    STATE(51), 1,
      sym_identifier,
  [1450] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(243), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1465] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1477] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_PERCENT_LT,
    ACTIONS(152), 3,
      ts_builtin_sym_end,
      sym__word,
      anon_sym_PERCENT_LT_EQ,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 3,
      anon_sym_RBRACK,
      anon_sym_field,
      anon_sym_unconnectedField,
  [1498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      sym_string,
  [1508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LBRACK,
  [1515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_GT_PERCENT,
  [1522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
  [1529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
  [1536] = 2,
    ACTIONS(265), 1,
      sym_comment,
    ACTIONS(267), 1,
      aux_sym_string_token1,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
  [1550] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
  [1557] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      ts_builtin_sym_end,
  [1564] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
  [1571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
  [1578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym__text_fragment,
  [1592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_GT_PERCENT,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LBRACE,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      sym__text_fragment,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LBRACE,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 59,
  [SMALL_STATE(7)] = 118,
  [SMALL_STATE(8)] = 175,
  [SMALL_STATE(9)] = 203,
  [SMALL_STATE(10)] = 252,
  [SMALL_STATE(11)] = 285,
  [SMALL_STATE(12)] = 336,
  [SMALL_STATE(13)] = 362,
  [SMALL_STATE(14)] = 388,
  [SMALL_STATE(15)] = 414,
  [SMALL_STATE(16)] = 440,
  [SMALL_STATE(17)] = 466,
  [SMALL_STATE(18)] = 493,
  [SMALL_STATE(19)] = 536,
  [SMALL_STATE(20)] = 563,
  [SMALL_STATE(21)] = 588,
  [SMALL_STATE(22)] = 613,
  [SMALL_STATE(23)] = 637,
  [SMALL_STATE(24)] = 661,
  [SMALL_STATE(25)] = 685,
  [SMALL_STATE(26)] = 709,
  [SMALL_STATE(27)] = 732,
  [SMALL_STATE(28)] = 754,
  [SMALL_STATE(29)] = 776,
  [SMALL_STATE(30)] = 812,
  [SMALL_STATE(31)] = 837,
  [SMALL_STATE(32)] = 866,
  [SMALL_STATE(33)] = 895,
  [SMALL_STATE(34)] = 924,
  [SMALL_STATE(35)] = 953,
  [SMALL_STATE(36)] = 982,
  [SMALL_STATE(37)] = 1008,
  [SMALL_STATE(38)] = 1034,
  [SMALL_STATE(39)] = 1060,
  [SMALL_STATE(40)] = 1086,
  [SMALL_STATE(41)] = 1112,
  [SMALL_STATE(42)] = 1138,
  [SMALL_STATE(43)] = 1164,
  [SMALL_STATE(44)] = 1190,
  [SMALL_STATE(45)] = 1209,
  [SMALL_STATE(46)] = 1227,
  [SMALL_STATE(47)] = 1245,
  [SMALL_STATE(48)] = 1263,
  [SMALL_STATE(49)] = 1282,
  [SMALL_STATE(50)] = 1295,
  [SMALL_STATE(51)] = 1314,
  [SMALL_STATE(52)] = 1333,
  [SMALL_STATE(53)] = 1348,
  [SMALL_STATE(54)] = 1361,
  [SMALL_STATE(55)] = 1380,
  [SMALL_STATE(56)] = 1399,
  [SMALL_STATE(57)] = 1418,
  [SMALL_STATE(58)] = 1431,
  [SMALL_STATE(59)] = 1450,
  [SMALL_STATE(60)] = 1465,
  [SMALL_STATE(61)] = 1477,
  [SMALL_STATE(62)] = 1489,
  [SMALL_STATE(63)] = 1498,
  [SMALL_STATE(64)] = 1508,
  [SMALL_STATE(65)] = 1515,
  [SMALL_STATE(66)] = 1522,
  [SMALL_STATE(67)] = 1529,
  [SMALL_STATE(68)] = 1536,
  [SMALL_STATE(69)] = 1543,
  [SMALL_STATE(70)] = 1550,
  [SMALL_STATE(71)] = 1557,
  [SMALL_STATE(72)] = 1564,
  [SMALL_STATE(73)] = 1571,
  [SMALL_STATE(74)] = 1578,
  [SMALL_STATE(75)] = 1585,
  [SMALL_STATE(76)] = 1592,
  [SMALL_STATE(77)] = 1599,
  [SMALL_STATE(78)] = 1606,
  [SMALL_STATE(79)] = 1613,
  [SMALL_STATE(80)] = 1620,
  [SMALL_STATE(81)] = 1627,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithBrackets, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_javascript, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_javascript, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 3, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 1, 0, 0), REDUCE(aux_sym__vectorWithoutBrackets_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__vectorWithBrackets_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__vectorWithoutBrackets, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(75),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(75),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(79),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(79),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 7, 0, 2),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 8, 0, 2),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 6, 0, 2),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__text_fragment = 0,
  ts_external_token_error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__text_fragment] = sym__text_fragment,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__text_fragment] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token__text_fragment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_wbproto_external_scanner_create(void);
void tree_sitter_wbproto_external_scanner_destroy(void *);
bool tree_sitter_wbproto_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_wbproto_external_scanner_serialize(void *, char *);
void tree_sitter_wbproto_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wbproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__word,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_wbproto_external_scanner_create,
      tree_sitter_wbproto_external_scanner_destroy,
      tree_sitter_wbproto_external_scanner_scan,
      tree_sitter_wbproto_external_scanner_serialize,
      tree_sitter_wbproto_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
